### ISSUE TITLE
geos  undefined: coordSeq

### ISSUE THREAD

**Issue by marwankous** [paulsmith/gogeos#33]
when i try to install the package i get the following message 

OS: ubuntu

go get  github.com/paulsmith/gogeos/geos
/go/pkg/mod/github.com/paulsmith/gogeos@v0.1.2/geos/coord.go:23:21: undefined: coordSeq
/go/pkg/mod/github.com/paulsmith/gogeos@v0.1.2/geos/helper.go:5:14: undefined: Geometry
exit status 2

**Comment by carlokuiper** [comment]
I had the same issue, but after setting CGO_ENABLED to 1 it worked for me.
`export CGO_ENABLED=1`
